### ISSUE TITLE
构建 target:browser 失败

### ISSUE THREAD

**Issue by zouhangwithsweet** [Simon-He95/transformToUnocss#14]
示例代码：`import { toUnocss } from 'transform-to-unocss'`
<img width="845" alt="image" src="https://github.com/Simon-He95/transformToUnocss/assets/21095710/cfc1ff1b-7739-4eb4-b6c1-c0e50c530251">

尝试单纯使用 toUnocss 方法时，构建面向浏览器产物时候，无法构建。是否可以提供一个纯函数导出，使其不依赖 `nodejs` 环境呢？

**Comment by Simon-He95** [comment]
Would you mind using [transform-to-unocss-core](https://github.com/Simon-He95/transform-to-unocss-core)? It will export toUnocss for browser
