### ISSUE TITLE
border transform error

### ISSUE THREAD

**Issue by zouhangwithsweet** [Simon-He95/transformToUnoCSS#18]
input: `border: 2px solid #e6e8ee;`

expect:
```css
border-2px border-solid border-#e6e8ee
```
actually:
```css
border-[2px_solid_#e6e8ee]
```
It's incorrect border color.
Maybe unocss could transform `border-[2px_solid_#e6e8ee]` to `border: 2px solid #e6e8ee;` not to `borde-color:2px solid #e6e8ee;`.

![image](https://github.com/Simon-He95/transformToUnoCSS/assets/21095710/3f43b2a4-c3ed-4201-9bcb-4631441e56b2)

**Comment by zouhangwithsweet** [comment]
Maybe it's unocss bug. What do you think?

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDmAnA9gVwAd0oQEAXBAWiUvIFMNdD6A7Esyq5tjBGcpHokAFhgDaMBHBgAKAIwAGRRBEB9KmoAs2egFsAlAF10APgBQUKMCSEErWIhQYcBQlXHjO1Hq1T9BCHojIwAuBgAPcioAT3o4OFwAdyoAdmUoM0srKBF4xOzgAHpbewsrGzsHeGQ0dAAjTCocBHA2aLgwVnoEbChG5uxWsHaPeQAORRB6TAAabEx6hFktcdmAJkUANlmtrVnFADp5dYM1RQBSWbUFpZW1zZ29g8PlM6VLk1Mtn63i0tYFmK4AgFnMoEg-Vw2Gm2Ak8kIETUSFwnRAN0Wy3WAGZsRtcfi8fJjGYoCdsfJscCIGBTEA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUdrQsE5vLD9mFmi1pjACABlKmhc5wAC8AD44AADL7BbQQeBklpwRKJGigexQfihAAMcAB4vFAFI4ABWOUAbi%2Bai%2B7K2FSoMCqGBA-0Qh2y0H2vKuwtFMLoTh8cxFPgFQpAIv4ZzOmK2VHV2KQQA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEAvkA

**Comment by Simon-He95** [comment]
I thought it could be done in this way at first, but it is true that unocss has no plan to support this writing method, and it is not supported in tailwind. I will open a PR to fix it.
