### ISSUE TITLE
css var transform error

### ISSUE THREAD

**Issue by zouhangwithsweet** [Simon-He95/transformToUnoCSS#20]
css var maybe include all atom class. Eg. `text-`, `bg-` ....

input: `color: var(--color, red);`

expect:
```css
text-[color:var(--default,red)]
```

actually:

```css
text-var(--color, red)
```
![image](https://github.com/Simon-He95/transformToUnoCSS/assets/21095710/155cd161-9129-4d78-80b2-dccabe2c91ce)

**Comment by zouhangwithsweet** [comment]
Error still here.
![image](https://github.com/Simon-He95/transformToUnoCSS/assets/21095710/bd1fea3b-43b4-45c4-aca1-d8c299476513)

**Comment by Simon-He95** [comment]
<img width="750" alt="image" src="https://github.com/Simon-He95/transformToUnoCSS/assets/57086651/8910391d-cb9f-4ca9-882c-b3b52ed52656">

**Comment by Simon-He95** [comment]
It’s just that the website doesn’t need to be redeployed

**Comment by zouhangwithsweet** [comment]
<img width="640" alt="image" src="https://github.com/Simon-He95/transformToUnoCSS/assets/21095710/4b520a4d-d0f8-45af-ab5a-7c2d7ecce1ae">
I just test in figma. I guess it's about the space in `var(--world-peas-compost-base, #000);` between `,` with `#`. It should be `var(--world-peas-compost-base,#000);`

**Comment by zouhangwithsweet** [comment]
Yes. I use the latest. My result like this.

<img width="1268" alt="image" src="https://github.com/Simon-He95/transformToUnoCSS/assets/21095710/d63d21ea-2cee-4bae-8525-25f88e42e3ae">

**Comment by Simon-He95** [comment]
> Yes. I use the latest. My result like this.
> 
> <img alt="image" width="1268" src="https://user-images.githubusercontent.com/21095710/285241413-d63d21ea-2cee-4bae-8525-25f88e42e3ae.png">

I made some adjustments and may try again
