### ISSUE TITLE
background image multi value transform error

### ISSUE THREAD

**Issue by zouhangwithsweet** [Simon-He95/transformToUnoCSS#24]
input: 
```css
background: linear-gradient(90deg, rgba(39, 175, 106, 0.20) 0%, rgba(102, 216, 77, 0.20) 100%), linear-gradient(0deg, rgba(102, 215, 77, 0.16) 0%, rgba(255, 255, 255, 0.00) 100%)
```
output:
```css
bg-gradient-linear bg-gradient-[0deg,rgba(102,215,77,0.16)_0%,rgba(255,255,255,0.00)_100%]
```

**Comment by zouhangwithsweet** [comment]
Actually I dont know the correct result should  be what. : )

**Comment by zouhangwithsweet** [comment]
input:
```css
background: var(--sim-col, linear-gradient(90deg, #25AE6A 0%, #68D94B 100%));
```
transform error

**Comment by Simon-He95** [comment]
In fact, I don’t know how to deal with this. It seems that currently unocss cannot convert this situation through inline styles.

**Comment by zouhangwithsweet** [comment]
Sure. I will do some research.

**Comment by Simon-He95** [comment]
> input:
> 
> ```css
> background: var(--sim-col, linear-gradient(90deg, #25AE6A 0%, #68D94B 100%));
> ```
> 
> transform error

fixed in transform-to-unocss-core v.0.0.23
