### ISSUE TITLE
插件在vite中的使用

### ISSUE THREAD

**Issue by bft2249228496** [Simon-He95/transformToUnoCSS#26]
import { viteTransformToUnocss } from 'transform-to-unocss'
 plugins:[viteTransformToUnocss(/* options */)]
1.请问在vite中是这样使用吗
2./*options */需要替换成什么吗，还是直接默认就行
3.如果遇到翻译不了的css样式，会自动忽略吗，还是直接报错

**Comment by Simon-He95** [comment]
默认就可以了，方在unocss插件前面，遇到转换不了的style和css会保留

**Comment by bft2249228496** [comment]
大佬，你好，我这边又尝试了一下，还是不行，只要装上插件使用就会出现图片中报错
![Snipaste_2024-03-25_14-49-33](https://github.com/Simon-He95/transformToUnoCSS/assets/59632188/ea48881c-48f0-49a1-bd5b-96fadedc9a91)
![Snipaste_2024-03-25_14-50-51](https://github.com/Simon-He95/transformToUnoCSS/assets/59632188/0e828ce5-e796-431f-9129-a5123f9826d3)

**Comment by Simon-He95** [comment]
这种动态的sass变量和extend的语法应该做不到😂，可以发一个简单的sass语法的vue的demo项目给我，调试看看

**Comment by bft2249228496** [comment]
主要是这个是后管项目的APP.vue里面的一些默认样式，我怕删掉会带来奇怪的问题，这个插件像这种解析不了的情况不能忽略吗。不行的话，回头我弄个demo试一下吧

**Comment by bft2249228496** [comment]
大佬，我在自己的demo里试了一下，好像是less的支持是有点问题，不知道和版本有没有关系。scss正常。普通css写法，没有用任何less特有的东西，只是style的lang定义为less，就会发生以下报错,改成scss就正常。
![Snipaste_2024-03-26_09-05-51](https://github.com/Simon-He95/transformToUnoCSS/assets/59632188/17eaa370-6194-4238-a1f3-13ef80f890b3)
![Snipaste_2024-03-26_09-08-32](https://github.com/Simon-He95/transformToUnoCSS/assets/59632188/db2a2f67-f4df-4d84-95cc-ef8e327ecc8c)
![Snipaste_2024-03-26_09-09-41](https://github.com/Simon-He95/transformToUnoCSS/assets/59632188/15eae750-fcf7-4690-ac8f-bf8845311865)

**Comment by Simon-He95** [comment]
demo发我一下呗

**Comment by bft2249228496** [comment]
好的，不知道怎么发，就建了一个仓库，大佬有空看下https://github.com/bft2249228496/vue3-git-help.git

**Comment by Simon-He95** [comment]
> 好的，不知道怎么发，就建了一个仓库，大佬有空看下https://github.com/bft2249228496/vue3-git-help.git

it's private

**Comment by bft2249228496** [comment]
我的，没注意，已经改了，大佬再看一下

**Comment by Simon-He95** [comment]
> 我的，没注意，已经改了，大佬再看一下

用最新的版本试一下那个less的错误应该没有了

**Comment by bft2249228496** [comment]
好的，我一会试一下，如果用scss的时候无法避免使用scss变量$prefix-cls: #{$namespace}-app;和@extend .size;这种，它识别不了，能不能让它不去处理，而不是直接报错

**Comment by Simon-He95** [comment]
> 好的，我一会试一下，如果用scss的时候无法避免使用scss变量$prefix-cls: #{$namespace}-app;和@extend .size;这种，它识别不了，能不能让它不去处理，而不是直接报错

好像现在是不会报错的，理论上是能被sass-loader编译出来，不知道里面会不会有啥问题，可以方便再提供一个sass 存在变量和extend的复杂的demo，方便进一步确认

**Comment by bft2249228496** [comment]
好的，代码已提交，大佬有空再看一下，还是那个demo

**Comment by Simon-He95** [comment]
@bft2249228496 试一下0.0.77，在github上交流不方便，可以来群里联系
![image](https://github.com/Simon-He95/transformToUnoCSS/assets/57086651/ad7e697b-e937-4a88-a0f8-09b25fe8333f)
