### ISSUE TITLE
grid-cols- 转换有问题

### ISSUE THREAD

**Issue by haobarry** [Simon-He95/transformToUnoCSS#28]
{
  grid-template-columns:120px auto;
}
转出来是这个  
grid-cols-120px auto

**Comment by Simon-He95** [comment]
thx~, has fixed
<img width="794" alt="image" src="https://github.com/Simon-He95/transformToUnoCSS/assets/57086651/89a17ff7-d712-481b-aafa-419d2dbbaa7c">
